LabWeb5/LabWeb5/Areas/Admin/Models/Produit.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace LabWeb5.Areas.Admin.Models
{
    public class Produit
    {
        public int Id { get; set; }

        [Display(Name = "Nom")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La description est requise.")]
        [StringLength(50, ErrorMessage = "Le code ne doit pas avoir plus de {1} caractères.")]
        public string Nom { get; set; } = string.Empty;



        public Produit()
        {

        }

        public Produit(string nom, int id)
        {
            Nom = nom;
            Id = id;
        }
    }
}

LabWeb5/LabWeb5/Areas/Admin/Models/Reservation.cs
using System.ComponentModel.DataAnnotations;
using System.Globalization;
using System.Xml.Linq;

namespace LabWeb5.Areas.Admin.Models
{
    public class Reservation
    {

        public DateTime Date { get; set; }


        [Display(Name = "Nom")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "La description est requise.")]
        [StringLength(50, ErrorMessage = "Le Nom ne doit pas avoir plus de {1} caractères.")]
        public string Nom { get; set; }


        [Display(Name = "Courriel")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "Le Courriel est requis.")]
        [StringLength(75, ErrorMessage = "Le Courriel ne doit pas avoir plus de {1} caractères.")]
        public string Courriel { get; set; }

        [Display(Name = "Menu")]
        [Range(1, short.MaxValue, ErrorMessage = "Le Menu est requis.")]
        [Required(ErrorMessage = "Le Menu est requis.")]
        public int ProduitId { get; set; }


        [Display(Name = "Nombre")]
        [Range(0, short.MaxValue, ErrorMessage = "La quantité en stock doit être positive.")]
        [Required(ErrorMessage = "Le nombre est requis.")]
        public int Nombre { get; set; }


        public int Id { get; set; }

        public Reservation()
        { 
        }
        public Reservation(DateTime date, string nom,string courriel, int produitId, int nbPersonnes, int id)
        {
            Date = DateTime.Now;
            Nom = nom;
            Courriel = courriel;
            ProduitId = produitId;
            Nombre = nbPersonnes;
            Id = id;
        }
    }
}

LabWeb5/LabWeb5/Areas/Admin/ViewModels/MenuListVM.cs
using LabWeb5.Areas.Admin.Models;
namespace LabWeb5.Areas.Admin.ViewModels
{
    public class MenuListVM
    {
        public List<Produit> Produits;
        
        public MenuListVM(List<Produit> produits)
        {
            Produits = produits;
        }
    }
}

LabWeb5/LabWeb5/Areas/Admin/ViewModels/ProductCreateEditVM.cs
using LabWeb5.Areas.Admin.Models;

namespace LabWeb5.Areas.Admin.ViewModels
{
    public class ProductCreateEditVM
    {
        public Produit Produit { get; set; } = new Produit();

        public ProductCreateEditVM()
        {
        }

        public ProductCreateEditVM(Produit product)
        {
            Produit = product;
        }
    }
}

LabWeb5/LabWeb5/ViewModels/ReservationListVM.cs
using LabWeb5.Areas.Admin.Models;

namespace LabWeb5.ViewModels
{
    public class ReservationListVM
    {
        public List<Reservation> reservation;

        public ReservationListVM(List<Reservation> res)
        {
            reservation = res;
        }
    }
}

LabWeb5/LabWeb5/ViewModels/SiteMessageVM.cs
namespace LabWeb5.ViewModels
{
    public class SiteMessageVM
    {
    }
}

LabWeb5/LabWeb5/Areas/Admin/Controllers/MenuChoiceController.cs
using Microsoft.AspNetCore.Mvc;
using LabWeb5.Areas.Admin.DataAccessLayer;
using LabWeb5.Areas.Admin.DataAccessLayer.Factories;
using LabWeb5.Areas.Admin.ViewModels;
using LabWeb5.Areas.Admin.Models;

namespace LabWeb5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenuChoiceController : Controller
    {
        public IActionResult List()
        {
            DAL dal = new DAL();
            ProductFactory facto = dal.ProductFact;
            MenuListVM vm = new MenuListVM(facto.GetAll());
            return View(vm);
        }

        [Area("Admin")]
        public IActionResult Edit(int id)
        {
            DAL dal = new DAL();
            ProductFactory facto = dal.ProductFact;
            return View(facto.Get(id));
        }
        [Area("Admin")]
        public IActionResult Create()
        {
            DAL dal = new DAL();

            ProductCreateEditVM viewModel = new ProductCreateEditVM(
                dal.ProductFact.CreateEmpty()
                );
            return View(viewModel);
        }
        [Area("Admin")]
        public IActionResult Delete(int id)
        {
            DAL dal = new DAL();
            ProductFactory p = dal.ProductFact;
            return View(p.Get(id));
        }

        [HttpPost]
        public IActionResult Edit(Produit p)
        {
            DAL dal = new DAL();
            ProductFactory facto = dal.ProductFact;
            facto.Save(p);
           return RedirectToAction("List");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int id)
        {
            DAL dal = new DAL();
            ProductFactory facto = dal.ProductFact;
            facto.Delete(id);
            return RedirectToAction("List");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ProductCreateEditVM viewModel)
        {
            if (viewModel != null && viewModel.Produit != null)
            {
                DAL dal = new DAL();

                Produit? existingProduct = dal.ProductFact.GetByName(viewModel.Produit.Nom);
                if (existingProduct != null)
                {
                    // Il est possible d'ajouter une erreur personnalisée.
                    // Le premier paramètre est la propriété touchée (à partir du viewModel ici)

                    ModelState.AddModelError("Produit.Nom", "Le code de produit existe déjà.");
                }
                if (!ModelState.IsValid)
                {
                    // Si le modèle n'est pas valide, on retourne à la vue CreateEdit où les messages seront affichés.
                    // Le ViewModèle reçu en POST n'est pas complet (seulement les info dans le <form> sont conservées),
                    // il faut donc réaffecter les Catégories.

                    
                    return View(viewModel);
                }



                dal.ProductFact.Save(viewModel.Produit);
            }

            return RedirectToAction("List");
        }



    }
}

LabWeb5/LabWeb5/Areas/Admin/Controllers/ReservationController.cs
using LabWeb5.Areas.Admin.DataAccessLayer.Factories;
using LabWeb5.Areas.Admin.DataAccessLayer;
using LabWeb5.Areas.Admin.Models;
using LabWeb5.Areas.Admin.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using LabWeb5.ViewModels;

namespace LabWeb5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ReservationController : Controller
    {
        public IActionResult List()
        {
            DAL dal = new DAL();
            ReservationFactory facto = dal.ReservationFact;
            ReservationListVM vm = new ReservationListVM(facto.GetAll());
            return View(vm);
        }
    }
}

LabWeb5/LabWeb5/Controllers/HomeController.cs
using LabWeb5.Areas.Admin.DataAccessLayer;
using LabWeb5.Areas.Admin.DataAccessLayer.Factories;
using LabWeb5.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;

namespace LabWeb5.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Reservation r)
        {
            DAL dal = new DAL();
            ReservationFactory facto = dal.ReservationFact;
            facto.Save(r);

            return RedirectToAction("Details", "Reservation", r);
        }
        
    }
}

LabWeb5/LabWeb5/Controllers/ReservationController.cs
using LabWeb5.Areas.Admin.Models;
using Microsoft.AspNetCore.Mvc;

namespace LabWeb5.Controllers
{
    public class ReservationController : Controller
    {
        public IActionResult Details(Reservation r)
        {
            return View(r);
        }
    }
}

LabWeb5/LabWeb5/Areas/Admin/Views/MenuChoice/Create.cshtml
@model ProductCreateEditVM
@{
    ViewData["Title"] = "Liste des produits";
}

<div id="produit-list-page">
    <div class="row">
        <div class="col-12">
            <div class="page-title">
                <h2>Modifier un choix de menu</h2>
                
                <form asp-action="Create">
                    <label asp-for="Produit.Nom"></label>
                    <input type="hidden" asp-for="Produit.Id" />
                    <input asp-for="Produit.Nom" />
                    
                    <span asp-validation-for="Produit.Nom" class="text-danger"></span>
                    <input type="submit"/>
                </form>
            </div>
           
        </div>
    </div>
</div>

LabWeb5/LabWeb5/Areas/Admin/Views/MenuChoice/Delete.cshtml
@model Produit
@{
    ViewData["Title"] = "Liste des produits";
    
    
}

<div id="produit-list-page">
    <div class="row">
        <div class="col-12">
            <div class="page-title">
                <h2>Supprimer un choix de menu</h2>

                <form asp-action="DeletePost">
                    <label for="desc">Description :</label>
                    <input type="hidden" asp-for="Id" />
                    <h2>@Model.Nom</h2>
                    <input type="submit" />
                </form>

                <br/>
                <a asp-action="List">Retour à la liste des choix de menu</a>
            </div>

        </div>
    </div>
</div>

LabWeb5/LabWeb5/Areas/Admin/Views/MenuChoice/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LabWeb5/LabWeb5/Areas/Admin/Views/MenuChoice/List.cshtml
@model MenuListVM
@{
    ViewData["Title"] = "Liste des produits";
}

<div id="produit-list-page">
    <div class="row">
        <div class="col-12">
            <div class="page-title">
                <h2>Liste des choix de menu</h2>
            </div>
            <table class="table table-sm table-bordered table-striped table-hover">
                <tr>
                    <!--
                    <th>Code</th>
                    <th>Nom du produit</th>
                    <th>Catégorie</th>
                    <th>Quantité en stock</th>
                    -->
                    <!-- Permet d'utiliser l'attribut Display(Name="...") de propriété du modèle -->
                    <!-- Permet de gérer l'affichage du modèle à un seul endroit -->

                    
                    <th>@Html.DisplayNameFor(model => model.Produits[0].Nom)</th>
                    
                    <th>Actions</th>
                </tr>
                @if (Model.Produits.Count > 0)
                {
                    foreach (Produit produit in Model.Produits)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(model => produit.Nom)
                            </td>

                            <td >
                                <div style="text-align:center; display:inline-flex">
                                <a asp-area="Admin" asp-controller="MenuChoice" asp-action="Edit" asp-route-id="@produit.Id"><i class="fa-regular fa-pen-to-square"></i></a><p> | </p>
                                <a asp-area="Admin" asp-controller="MenuChoice" asp-action="Delete" asp-route-id="@produit.Id"><i class="fa-solid fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">Aucun produit trouvé.</td>
                    </tr>
                }
            </table>
            <div style="width:100%;text-align:center;">
                <a asp-action="Create">
                    Ajouter un choix de menu
                </a>
            </div>
        </div>
    </div>
</div>

LabWeb5/LabWeb5/Areas/Admin/Views/Reservation/Delete.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

LabWeb5/LabWeb5/Areas/Admin/Views/Reservation/List.cshtml
@using LabWeb5.ViewModels
@model ReservationListVM
@{
    ViewData["Title"] = "Liste des produits";
}

<div id="produit-list-page">
    <div class="row">
        <div class="col-12">
            <div class="page-title">
                <h2>Liste des choix de menu</h2>
            </div>
            <table class="table table-sm table-bordered table-striped table-hover">
                <tr>

                    <th>@Html.DisplayNameFor(model => model.reservation[0].Date)</th>
                    <th>@Html.DisplayNameFor(model => model.reservation[0].Nom)</th>
                    <th>@Html.DisplayNameFor(model => model.reservation[0].Courriel)</th>
                    <th>@Html.DisplayNameFor(model => model.reservation[0].ProduitId)</th>
                    <th>@Html.DisplayNameFor(model => model.reservation[0].Nombre)</th>
                    
                    <th>Actions</th>
                </tr>
                @if (Model.reservation.Count > 0)
                {
                    foreach (Reservation res in Model.reservation)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(model => res.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(model => res.Nom)
                            </td>
                            <td>
                                @Html.DisplayFor(model => res.Courriel)
                            </td>
                            <td>
                                @Html.DisplayFor(model => res.ProduitId)
                            </td>
                            <td>
                                @Html.DisplayFor(model => res.Nombre)
                            </td>
                            <td>
                                    <a asp-area="Admin" asp-controller="Reservation" asp-action="Delete" asp-route-id="@res.Id"><i class="fa-solid fa-trash"></i></a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td colspan="5">Aucune reservation trouvée.</td>
                    </tr>
                }
            </table>
        </div>
    </div>
</div>

LabWeb5/LabWeb5/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Démo Admin</title>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.no-icons.min.css" rel="stylesheet">
    <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">


    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" />

    <link rel="stylesheet" href="~/Admin/assets/css/admin-bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Admin/assets/css/admin.css" asp-append-version="true" />

    @await RenderSectionAsync("Links", required: false)
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" asp-controller="home" asp-action="index">
                ADMINISTRATION
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" asp-area="List" asp-controller="MenuChoice" asp-action="List">LES CHOIX DE MENU</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="List" asp-action="Reservation">LES RÉSERVATIONS</a>
                    </li>

                </ul>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            <a asp-area="Admin" asp-controller="MenuChoice" asp-action="List">Les choix de menu</a> 
            <a asp-area="Admin" asp-controller="Reservation" asp-action="List">Les réservations</a>
        </div>
        <div>
            <b>ASP.NET MVC - Alexandre Perron</b>
        </div>
    </footer>

    <!-- Placé à la fin du document pour un chargement plus rapide des pages -->
    <!-- Ordre : jQuery, Popper.js, puis Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"></script>

    <script src="~/Admin/assets/js/admin.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

LabWeb5/LabWeb5/Views/Reservation/Details.cshtml
@model Reservation

@{
    ViewData["Title"] = "Liste des produits";
    
    
}

<div id="produit-list-page">
    <div class="row">
        <div class="col-12">
            <div class="page-title">
                <h2>Réservation complétée avec succès</h2>

                    <h2 style="font-weight:bolder">Nom :</h2><br/>
                <h2> @Model.Nom </h2><br /><br />
                <h2 style="font-weight:bolder">Courriel :</h2><br />
                <h2> @Model.Courriel </h2><br /><br />
                <h2 style="font-weight:bolder">Nombre :</h2><br/>
                <h2> @Model.Nombre </h2><br /><br />
                <h2 style="font-weight:bolder">Date :</h2><br />
                <h2> @Model.Date></h2><br /><br />
                <h2 style="font-weight:bolder">Choix de menu :</h2><br />
                <h2> @Model.ProduitId </h2><br /><br />
                

                <br/>
                <a asp-controller="Home" asp-action="index">Retour à la page d'accueil</a>
            </div>

        </div>
    </div>
</div>

LabWeb5/LabWeb5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Démo ASP.NET Core</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/fontawesome.min.css" />

    <link rel="stylesheet" href="~/css/site-bootstrap.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

    <!--
        Section qui permet d'ajouter du contenu dans <head> à partir d'une vue
        Voir la vue Contact/Index.cshtml pour un exemple.
    -->
    @await RenderSectionAsync("Links", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <a class="navbar-brand" asp-controller="home" asp-action="index">
                RÉSERVATION EN LIGNE
            </a>
        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">
            ASP.NET MVC - Alexandre Perron
        </div>
    </footer>

    <!-- Placé à la fin du document pour un chargement plus rapide des pages -->
    <!-- Ordre : jQuery, Popper.js, puis Bootstrap JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.11.6/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--
        Section qui permet d'ajouter du JavaScript à partir d'une vue
        Voir la vue Contact/Index.cshtml pour un exemple.
    -->
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>